### ISSUE TITLE
why not use Github API?

### ISSUE THREAD

**Issue by zjuchenyuan** [Hell0W0rld0/Github-Hunter#1]
https://developer.github.com/v3/search/#search-code

似乎Github提供的搜索API已经能满足你的需求，请问使用模拟登录是有其他的考虑吗？

**Comment by Hell0W0rld0** [comment]
谢谢您的反馈，看了下search-code的返回值，没有code的具体内容。还是会得到一个url，有了url后还是要去请求后返回内容，再进行payload匹配。所以就用的爬虫来解析内容的。
