### ISSUE TITLE
Problem with NoneType

### ISSUE THREAD

**Issue by NooAn** [Hell0W0rld0/Github-Hunter#6]
登陆成功，正在检索泄露信息.......
  0%|                                                                                                                                                                        | 0/6 [00:00<?, ?it/s]Exception KeyError: KeyError(<weakref at 0x7f9772196f18; to 'tqdm' at 0x7f9772186490>,) in <bound method tqdm.__del__ of   0%|                                                                                                                                                                        | 0/6 [00:01<?, ?it/s]> ignored
'encoding' is an invalid keyword argument for this function
str() takes at most 1 argument (2 given)
Traceback (most recent call last):
  File "GithubHunter.py", line 188, in <module>
    tUrls, codes= hunter(g_User, g_Pass, keywords)
TypeError: 'NoneType' object is not iterable

**Comment by Hell0W0rld0** [comment]
Maybe something wrong with tqdm, please update it or reinstall it . Thanks.
